### PR TITLE
SMM Cheats

### PR DESCRIPTION
**Pull request by Souperman9**
Working SMM cheats.

### CODE REVIEW

**Comment by Souperman9** [comment]
I tested every cheat. Most of them didn't work, so I got rid of those.

**Comment by JourneyOver** [comment]
@Souperman9 So you tested these https://github.com/BernardoGiordano/Sharkive/blob/master/db/00040000001A0400.txt and all of the ones that didn't have a version (or had a version) in the name didn't work? one thing to do is add back the ones that have a version on them if they worked on older versions of the game, as we tend to keep lower version codes around still as some people tend to not play on the latest version of games sometimes. Just swap things around so that it goes from newest versions to oldest versions.

**Comment by Souperman9** [comment]
That's strange... I didn't know there were codes in the database. When I used Sharkive it didn't say there were any. I'll test those. (These codes are ones I found online.)

**Comment by JourneyOver** [comment]
If your using the EU version of the game then the codes from the link I provided above more than likely will not work as they are for the US version of the game. There is currently no EU version in the DB so that is why sharkive said there was none in the DB for you.

So what I would say is that you either
1. Redo this PR so it only consists of the EU version codes and not remove any of the US version codes.
or
2. Test both US version and EU version games and figure out everything that works for both versions. Because codes that work for one region might not work for another region.

**Comment by Souperman9** [comment]
I'll test these for the EU version and add the ones online to it.

**Comment by JourneyOver** [comment]
okay, then I'd say backtrace on the whole US version changes you did, as in either go in and replace the US .txt file with the old one and update the PR, or you can close this PR and refork and just add in the EU version and resubmit the new PR.

**Comment by Souperman9** [comment]
I'll delete the fork, make another one, and add the working codes for EU (with extra ones).

**Pull request closed without merging**
