### PR TITLE
Update 0004000000197100.txt

### PR DESCRIPTION
**Pull request by xzyx1997**
I found this on the web.

### CODE REVIEW

**Comment by BernardoGiordano** [comment]
did you test them?

**Comment by xzyx1997** [comment]
No, but you can look at this.

https://gbatemp.net/threads/gateway-cheats.402900/page-187#post-8170426

**Comment by xzyx1997** [comment]
No, but you can look at this.

https://gbatemp.net/threads/gateway-cheats.402900/page-187#post-8170426

**Comment by xzyx1997** [comment]
It has been tested for use

**Comment by JourneyOver** [comment]
As in it has been tested with luma cheats menu, as currently it notes for both codes 

> This code can be used only GateWay3DS.

**Comment by xzyx1997** [comment]
加工屋で生産できる武器、防具、装飾品全開+素材不要
[Complete produce equipment list & No need materials v1.3]
00B008E8 E3A00001
00B0081C E3A00001
00AD8864 E3A00001
0017B574 E3A00063
0017C1A4 E3A00001
50BF2CAC 00000000
00BF2CA8 00000010
D0000000 00000000
60BF2CA8 00000000
D9000000 00BF2CA8
D4000000 FFFFFFFF
D6000000 00BF2CA8
D0000000 00000000
D3000000 00000000
50BF2CA8 00000001
B0BF2CAC 00000000
50041CE8 E5DA0004
00041CE8 E3A00004
D0000000 00000000
5003DC2C 0A000001
0003DC2C E1A00000
D0000000 00000000
5004478C 0A000044
0004478C E1A00000
D0000000 00000000
D0000000 00000000
D3000000 00000000
B0D91A40 00000000
B0000070 00000000
C0000000 00000020
60000214 000E9000
DC000000 00000030
D0000000 00000000
D1000000 00000000
D9000000 00000210
D3000000 00000000
D6000000 00BF2CAC
D3000000 00000000
This can be used

**Comment by JourneyOver** [comment]
So you tested that and it worked for you? but the other one doesn't work?

**Comment by xzyx1997** [comment]
Yes, the other one is not tested

**Comment by JourneyOver** [comment]
Well then either test both of them to confirm that both work or remove the one you have not tested, and I will merge this PR.

**Comment by JourneyOver** [comment]
Thank you :)

**Pull request merged**
